version: '3'
services:
  voting-storage:
    build: /src/storage/2.0
    image: mcr.microsoft.com/aks/samples/voting/storage:2.0
    container_name: voting-storage
    env_file: storage.env
    ports:
        - "3306:3306"

  voting-app:
    build: /src/app/2.0
    image: mcr.microsoft.com/aks/samples/voting/app:2.0
    container_name: voting-app
    env_file: app.env
    ports:
        - "8080:8080"
    depends_on:
     - voting-analytics
     - voting-storage

  voting-analytics:
    build: /src/analytics/2.0
    image: mcr.microsoft.com/aks/samples/voting/analytics:2.0
    container_name: voting-analytics
    env_file: analytics.env
    ports:
        - "8082:8082" # port used in analytics.env
    depends_on:
     - voting-storage